language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-yogurt' ]; then cd .. && eval "mv $currentfolder generator-yogurt" && cd generator-yogurt; fi

